import { ScanFace, ShieldCheck, Fingerprint } from 'lucide-react';
export const services = [
 { id: 'credit-verification', title: 'Credit Verification Platform', short: 'Connect your field teams and credit analysts. Keep verification information organized, from the first visit to the final review.', icon: ShieldCheck, features: ['Credit point verification (CPV)', 'Risk containment unit (RCU) support', 'Field and back-office collaboration'] },
 { id: 'ekyc', title: 'eKYC Verification', short: 'Simplify customer onboarding with document checks, face matching, and video KYC in one connected workflow.', icon: ScanFace, features: ['Passport, national ID and visa OCR', 'Face matching', 'Video KYC solutions'] },
 { id: 'identity-verification', title: 'Identity Verification', short: 'Build confidence in who you are doing business with. Bring identity checks directly into your onboarding experience.', icon: Fingerprint, features: ['AI-powered verification APIs', 'Digital onboarding integration', 'Identity checks for financial services'] },
];
export const articles = [
 { slug: 'connecting-field-teams', category: 'Credit verification', title: 'Connecting field teams and credit analysts', excerpt: 'Why a shared verification workflow matters, from a field visit to a lending review.', sections: [{title:'Start with consistent information',body:'Credit verification involves people working in different places. A shared checklist helps field teams collect the information that back-office analysts need, without relying on scattered messages and documents.'},{title:'Make the handoff clear',body:'Each verification should have a clear owner and a visible status. Organizing findings, supporting documents, and outstanding questions together helps analysts review the case and request clarification.'},{title:'Keep people in the loop',body:'Technology supports the process; it does not replace professional judgment. A connected workflow helps teams collaborate and make an informed review of each case.'}] },
 { slug: 'understanding-ekyc', category: 'Customer onboarding', title: 'A practical introduction to digital KYC', excerpt: 'Understand document recognition, face matching, and video verification without the jargon.', sections: [{title:'What is eKYC?',body:'Electronic Know Your Customer, or eKYC, is the process of checking a customer’s identity digitally. It can bring document review and identity checks into an online onboarding experience.'},{title:'Different checks serve different needs',body:'Optical character recognition (OCR) extracts information from identity documents. Face matching compares facial images. Video KYC allows a verification process to include a video interaction. The right combination depends on your institution’s requirements.'},{title:'Design around the customer',body:'Clear instructions, readable forms, and useful error messages matter as much as the checks themselves. Customers should understand what information is requested and what happens next.'}] },
 { slug: 'identity-verification', category: 'Identity & risk', title: 'Putting identity checks into your onboarding', excerpt: 'A clearer approach to choosing where identity verification fits in the customer journey.', sections: [{title:'Map your customer journey',body:'Begin by identifying where customers provide identity information and where your team reviews it. This helps reveal repeated requests and gaps in the process.'},{title:'Choose relevant verification checks',body:'Verification requirements vary by product, institution, and applicable regulation. Select checks that address those requirements and keep the customer experience understandable.'},{title:'Plan for exceptions',body:'Not every check will produce an immediate result. Give your team a clear process for reviewing exceptions, requesting additional information, and communicating the next step to a customer.'}] },
];
export function pageHead(title: string, description: string) {
 const fullTitle = `${title} — Coppers`;
 return { meta: [{ title: fullTitle }, { name: 'description', content: description }, { property: 'og:title', content: fullTitle }, { property: 'og:description', content: description }, { property: 'og:type', content: 'website' }, { name: 'twitter:card', content: 'summary_large_image' }] };
}
